POST https://cse341node-getzels.herokuapp.com/contacts
Content-Type: application/json

{
  "firstName": "Vicenta",
  "lastName": "De Los Santos",
  "email": "vicenta@test.com",
  "favoriteColor": "blue",
  "birthday": "1988-06-26T04:00:00.000Z"
}

###

DELETE https://cse341node-getzels.herokuapp.com/contacts/62a57f487ca1edfe71d96421 HTTP/1.1
Content-Type: application/json

###

POST https://cse341node-getzels.herokuapp.com/contacts/62a57f487ca1edfe71d96424
Content-Type: application/json

{
  "firstName": "Vicenta",
  "lastName": "Frias Arias",
  "email": "vicenta@test.com",
  "favoriteColor": "blue",
  "birthday": "1988-06-26T04:00:00.000Z"
}

###
GET https://cse341node-getzels.herokuapp.com/contacts HTTP/1.1
Content-Type: application/json

###

GET https://cse341node-getzels.herokuapp.com/contacts/62a57f487ca1edfe71d96424 HTTP/1.1
Content-Type: application/json


